const express = require('express')
const router = express.Router()
const authRouter = require('./auth')
const userRouter = require('./users')
const adminRouter = require('./admin')
const bookOrderRouter = require('./bookOrder')
const walletRouter = require('./wallet')
const subscriptionRouter = require('./subscription')
const utilsRouter = require('./utils')
const intakeUserRouter = require('./intake-user')
const washDryRouter = require('./wash-dry')
const pressIronRouter = require('./press-iron')
const sortPretreatRouter = require('./sort-pretreat')
const qcUserRouter = require('./qc')
const notificationRouter = require('./notification')
const riderRouter = require('./rider')
const seedRouter = require('./seed')
const searchRouter = require('./search')


router.use('/admin', adminRouter)
router.use('/users', userRouter)
router.use('/auth', authRouter)
router.use('/bookOrder', bookOrderRouter)
router.use('/wallet', walletRouter)
router.use('/subscription', subscriptionRouter)
router.use('/utils', utilsRouter)
router.use('/intake-user', intakeUserRouter)
router.use('/press-iron', pressIronRouter)
router.use('/wash-dry', washDryRouter)
router.use('/sort-pretreat', sortPretreatRouter)
router.use('/rider', riderRouter)
router.use('/seeds', seedRouter)
router.use('/seeds', seedRouter)
router.use('/search', searchRouter)
router.use('/qc-user', qcUserRouter)
router.use('/notifications', notificationRouter)

module.exports = router